spring:
  profiles:
    active: dev #指定为开发环境

#数据库配置
  datasource:
    url: jdbc:mysql://192.168.6.128:3306/goods?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: liu521
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      web-stat-filter:
        enabled: false
      goods:
        url: jdbc:mysql://192.168.6.128:3306/goods?useUnicode=true&characterEncoding=utf8&autoReconnect=true


#redis 配置
redis:
  type: standalone
  config :
    type: manual
  host: 10.189.1.141
  port: 6379
  password:
  maxIdle: 500
  maxTotal: 500
  maxWaitMillis: -1    

  timeout:
    accessTokenTimeout:  1200 #访问token失效时间 单位秒
    refreshTokenTimeout: 1800 #刷新token失效时间 单位秒
    captchaTimout:  120       #验证码失效时间 单位秒
    smscodeTimout: 120        #短信验证码失效时间 单位秒
  isDemoSite: no
  ssl: off #是否开启ssl
foo: fooversion

        
